In [5]:
import numpy as np

QUESTION 1


In [6]:
A = np.array([[2,-1],[0,3]])
B = np.array([[1,2],[-3,4]])

#For question 1(a)
print(A+B)

#For question 1(b)
print(A @ B)

#For question 1(c)
print(3*A-2*B)

[[ 3  1]
 [-3  7]]
[[ 5  0]
 [-9 12]]
[[ 4 -7]
 [ 6  1]]


QUESTION2

In [7]:
det = round(np.linalg.det(A),2)
print(f"The determinant of matrix A is: {det}")

print()
#For question 2(b)
if(not det==0):
    print("Inverse of matrix A exists.")
    inverse = np.linalg.inv(A)
    print("The inverse of the matrix A is:")
    print(inverse)
else:
    print("Inverse of matrix A doesn't exist.")

The determinant of matrix A is: 6.0

Inverse of matrix A exists.
The inverse of the matrix A is:
[[0.5        0.16666667]
 [0.         0.33333333]]


QUESTION3

In [8]:
C = np.array([[4,1],[-2,1]])
egval,egvec = np.linalg.eig(A)
print(f"The eigen values of matrix A are: {egval}")
print()
print(f"The eigen vectors of matrix A are: {egvec}")

The eigen values of matrix A are: [2. 3.]

The eigen vectors of matrix A are: [[ 1.         -0.70710678]
 [ 0.          0.70710678]]


QUESTION4

In [9]:
X = np.array([
    [1, 4, 1.5, 100],  # Car 1
    [1, 6, 2.0, 150]   # Car 2
])
y = np.array([20, 30])  # Prices of cars 1 and 2

# Compute coefficients (beta) using the pseudo-inverse
X_transpose = X.T
beta = np.linalg.pinv(X_transpose @ X) @ X_transpose @ y

# Features for car 3 (including the bias term)
car_3_features = np.array([1, 8, 3.0, 200])

# Predict the price of car 3
price_car_3 = car_3_features @ beta

# Output the result
print(f"The predicted price of car 3 is: {price_car_3:.2f}")

The predicted price of car 3 is: 40.00
